In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Array with Arry functions

In [4]:
#adding array's on an element to element bases 
# adding arr to itself
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
#Subtracting arrays on element by ellement bases 
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#Multiplying array's on element by element basis 
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Scaller functions 

In [13]:
#Scaller opertaion is to perform arytmatic on a element by element bases 
arr * (10 / 2 + 3 - 60)**2

array([    0.,  2704.,  5408.,  8112., 10816., 13520., 16224., 18928.,
       21632., 24336., 27040.])

When performing arytmatic with arrays and a error is encountered numPy will only issue a warning

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#The first element in the array is 0 and 0/0 will present an erro. 
arr / arr

C:\Users\raymondk\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Universal Array Functions

In [15]:
#Retuning the square rout of every element a array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [17]:
#Returning the exponential of every element in the array
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [18]:
#Returning the max of an array
np.max(arr)

10

In [19]:
np.average(arr)

5.0

In [21]:
np.min(arr)

0