# Numpy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#Returning the value at index 8 from the array
arr[8]

8

In [6]:
#Returning all the value in a range of index positions from the arr 
arr[1:5]

array([1, 2, 3, 4])

In [7]:
#returning all the vaules until index value 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
#Returning all the values from a given index position onwards 
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
#using broadcasting to change the first 5 values of the array to 100 
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
#resetting the array 
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Slicing an array to a new variable and then using broadcasting on that variable the original array will also be affected

In [11]:
#Creating a slice of the array
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
#Broadcasting all the values of the slice to 99 and returning the original array, will show the orriginal array is also changed
slice_arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
#Returning slice of the array
slice_arr

array([99, 99, 99, 99, 99, 99])

Prventing the orriginal array the slice to a new variable must make use of the copy function 

In [14]:
#Creating a new slice of the array 
copy_arr = arr.copy()

In [15]:
#Broadcasing the values of the copied array to 100
copy_arr[:] = 100
copy_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
#Returning the original array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2d array

In [17]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [18]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
#Returning index position 2 of row 0 i.e 15
arr_2d[0,2]

15

In [20]:
#Returning sections of the 2 d array i.e retruning the first 2 rows but from column index 1 onwards
arr_2d [:2,1:]

array([[10, 15],
       [25, 30]])

In [21]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

# Conditional selection

In [22]:
newarr = np.arange(1,11)

In [23]:
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Using comparison opperator to get a boolean array 
newarr >5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
#selecting all values where the values are greater than 5 in single line 
newarr[newarr > 5]

array([ 6,  7,  8,  9, 10])

In [31]:
#Returning all the elements of newarr where the values is less than 3
newarr[newarr < 3]

array([1, 2])

In [36]:
newarr_2d = np.arange(50).reshape(5,10)

In [37]:
newarr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
newarr_2d[1:3,4:6]

array([[14, 15],
       [24, 25]])